DROP DATABASE IF EXISTS base_datos;
CREATE DATABASE base_datos;
USE base_datos;
CREATE TABLE contacto( 
    id INT AUTO_INCREMENT PRIMARY KEY, 
    CODIGO VARCHAR(255),
    NOMBRE VARCHAR(255),
    TELEFONO VARCHAR(255),
    CORREO VARCHAR(255),
    DIRECCION VARCHAR(255)
);

